### ISSUE TITLE
Add optional support for returning messages as JSON

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [miss85246/sanic-dantic#3]
Hey there! Thanks so much for your work on this!

Would you be willing to accept a patch that adds the ability to specify if validation/assertion errors should be returned as text vs JSON as well as specify if they want to return the first error or all present errors?

My own local testing has yielded this (very) rough draft:

```python
def validate(request, header=None, path=None, query=None, form=None, body=None, return_json=False, send_first_error_only=True):
    """
    When there are the same parameter name in the model, the parameter in ParsedArgsObj will be overwritten,
    The priorities is: body = form > query > path \n
    :param header: Pydantic model
    :param request: Pydantic model
    :param query: Pydantic model
    :param body: Pydantic model, cannot exist at the same time as form
    :param path: Pydantic model
    :param form: Pydantic model, cannot exist at the same time as body
    :param return_json: Whether to return JSON instead of text
    :param send_first_error_only: Whether to send only the first error in the list or all errors
    :return parsed_args: ParsedArgsObj
    """
    try:
        error_message = "sanic-dantic: body model must be used together with one of ['POST','PUT','PATCH','DELETE']"
        assert request.method in ["POST", "PUT", "PATCH", "DELETE"] if body else True, error_message
        models, parsed_args = [header, path, query] + [form or body], ParsedArgsObj()
        body_storage = {k: v[0] if len(v) == 1 else v for k, v in request.form.items()} if form else request.json
        params = {k: v[0] if len(v) == 1 else v for k, v in request.args.items()}
        storages = [request.headers, request.match_info, params, body_storage]
        models = [item for item in zip(models, storages) if item[0]]
        [parsed_args.update(model(**storage).dict()) for model, storage in models]
    except ValidationError as e:
        errors = e.errors()
        if send_first_error_only:
            errors = [e.errors()[0]]

        request.ctx.sanic_dantic_validation_errors = errors

        message = '\n'.join([f'{msg.get("loc")[0]} {msg.get("msg")}' for msg in errors])

        if not return_json:
            request.ctx.sanic_dantic_validation_errors = message
            request.ctx.sanic_dantic_return_type = 'text'
        else:
            request.ctx.sanic_dantic_return_type = 'json'
        raise InvalidUsage(message)

async def catch_errors(request, exception):
  if hasattr(request.ctx, 'sanic_dantic_validation_errors'):
    logging.error(request.ctx.sanic_dantic_validation_errors)
    return getattr(sanic.response, request.ctx.sanic_dantic_return_type)(request.ctx.sanic_dantic_validation_errors, status=exception.status_code)

app.error_handler.add(InvalidUsage, catch_errors)
```

where validate is a reimplementation of `sanic_dantic.basic_definition.validate`, `catch_errors` is a stub for a custom error handler, and `app` is a predefined Sanic app.

I know it's not elegant, especially having to ask the user to register the handler themselves. Perhaps a better way would be to just attach the ValidationError to the context and let the user sort it out themselves if they want JSON?

The most important thing to me is being able to return all the errors at the same time. Implementation and everything else is secondary

**Comment by miss85246** [comment]
@rafmagns-skepa-dreag .

First of all, thanks for your affirmation and your suggestion.

I read your issue, but I'm not quite sure what you mean. 

Did you mean to return the exception caught by ValidationError as a Json object? 

In fact, for general request flow,  it is correct to throw a parameter exception when it is detected.

However, as you said, some people may need all the abnormal parameters, and I will consider adding this function.

Recently, Sanic will release v21.3. And I am busy to checking the translation of  `sanic-guide` to ensure that can be released simultaneously with Sanic v21.3.

Furthermore, `sanic-dantic` has not tested the compatibility of v21.3, and I am not sure whether it can be used normally on v21.3 now.

After the official release of Sanic v21.3, I will take some time to test the compatibility between `sanic-dantic` and Sanic v21.3

The next condition of `sanic-dantic` is support exception handling more friendly.

Thanks again for your suggestion！If you have any more ideas, please let me know !
